dist: precise
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
install: composer install
script:
  - vendor/phpunit/phpunit/phpunit